### ISSUE TITLE
Add PowerApps Checker reference to PPALM 

### ISSUE THREAD

**Issue by paulbreuler** [microsoft-d365-ce-pfe-devops/D365-CE-Pipelines#4]
Add a templated version of PowerApps checker to PPALM templates

**Comment by paulbreuler** [comment]
@tyler-hogsett-microsoft you already have a template for checker under another branch. Instead of recreating I want to leverage the same / similar. Do you plan merge that down to develop? And should it be under powerapps-build-tools?

**Comment by paulbreuler** [comment]
**Orchestration example:** 

``` yaml
variables:
  skipComponentGovernanceDetection: true

name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

resources:
  repositories:
    - repository: templates
      type: GitHub
      name: microsoft-d365-ce-pfe-devops/D365-CE-Pipelines
      endpoint: GitHub
      ref: refs/heads/feature/powerapps-build-tools

stages:
  - template: powerapps-build-tools/stages/build-with-jit.yml@templates
    parameters:
      name: 'Build_Test_Solution'
      vmImage: 'vs2017-win2016'
      buildEnvironment: 'Meecrosoft-Build'
      solutionName: '$(solution.name)'
      solutionPath: '$(solution.path)'
      powerAppsChecker.rulesetId: ''
      powerAppsChecker.clientId: ''
      powerAppsChecker.clientSecret: ''
      azure.geography: ''
      azure.tenantId: ''
  - template: powerapps-build-tools/stages/release.yml@templates
    parameters:
      name: 'Release_To_Test'
      dependsOn: 'Build_Test_Solution'
      vmImage: 'vs2017-win2016'
      targetEnvironment: 'Meecrosoft-Test'
      solutionName: '$(solution.name)'
  - template: powerapps-build-tools/stages/release.yml@templates
    parameters:
      name: 'Release_To_Production'
      dependsOn: 'Release_To_Test'
      vmImage: 'vs2017-win2016'
      targetEnvironment: 'Meecrosoft-Production'
      solutionName: '$(solution.name)'
```
